# ----------------------------------------------------------------------------
# Challenge 04 — Validations — runner (schema + tests)
#
# DO NOT EDIT THIS FILE. Your work goes in models/04_validations.rb —
# the brief is there too. Run with:  ruby 04_validations.rb
#
# The grader always uses the official copy of this file, so editing it
# cannot make anything pass. Reading it is encouraged: the tests below
# are the specification.
# ----------------------------------------------------------------------------

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"
  gem "activerecord", "~> 8.1"
  gem "sqlite3", "~> 2.9"
end

require "active_record"
require "minitest/autorun"

ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Migration.verbose = false

# ----------------------------------------------------------------------------
# SCHEMA
# ----------------------------------------------------------------------------

ActiveRecord::Schema.define do
  create_table :users do |t|
    t.string  :name
    t.string  :email
    t.string  :username
    t.integer :age # optional
  end
end

# ----------------------------------------------------------------------------
# MODELS — your work, loaded from the one file you edit
# ----------------------------------------------------------------------------

require_relative "models/04_validations"

# ----------------------------------------------------------------------------
# TESTS — ordered easy to hard
# ----------------------------------------------------------------------------

class ValidationsTest < Minitest::Test
  def self.test_order = :alpha

  VALID = { name: "Sam Doe", email: "sam@example.com", username: "samdoe", age: 25 }.freeze

  def setup
    User.delete_all
  end

  def test_1_a_fully_filled_user_is_valid
    assert User.new(VALID).valid?,
      "a user with a name, a real email, a free username and age 25 must be " \
      "valid — if this fails, one of your rules is too strict"
  end

  def test_2_name_and_email_are_required
    user = User.new(VALID.merge(name: nil, email: nil))

    refute user.valid?, "a user with no name and no email must not be valid"
    assert user.errors[:name].any?,
      "the missing name must put an error on :name"
    assert user.errors[:email].any?,
      "validations do not stop at the first failure — the email error must be " \
      "there too, so a form can show every problem at once"
  end

  def test_3_email_must_look_like_an_email
    refute User.new(VALID.merge(email: "not-an-email")).valid?,
      "an email without an @ is not an email"
    assert User.new(VALID.merge(email: "sam.doe@mail.example.org")).valid?,
      "dots and subdomains are normal — do not over-tighten the format"
  end

  def test_4_age_has_a_floor_but_is_optional
    refute User.new(VALID.merge(age: 12)).valid?,
      "users must be 13 or older"
    assert User.new(VALID.merge(age: nil)).valid?,
      "age is optional — a rule about wrong ages must not reject missing ones. " \
      "This distinction (invalid vs absent) is the one people get wrong."
  end

  def test_5_username_is_unique_ignoring_case
    User.create!(VALID)
    dup = User.new(VALID.merge(email: "other@example.com", username: "SamDoe"))

    refute dup.valid?,
      "samdoe is taken, so SamDoe must be rejected — usernames that differ " \
      "only by case are the same username. Plain uniqueness is not enough here."
  end

  def test_6_reserved_usernames_are_rejected_exactly
    %w[admin root].each do |taken|
      user = User.new(VALID.merge(username: taken))
      refute user.valid?, "#{taken} is reserved and must be rejected"
      assert user.errors[:username].any?,
        "the reserved-name error must be attached to :username — " \
        "a validation adds to errors, it never raises"
    end

    assert User.new(VALID.merge(username: "administrator")).valid?,
      "administrator is NOT on the reserved list — the check is an exact " \
      "match, not a substring match"
  end
end
