# ----------------------------------------------------------------------------
# Challenge 05 — Polymorphic associations — runner (schema + tests)
#
# DO NOT EDIT THIS FILE. Your work goes in models/05_polymorphic.rb —
# the brief is there too. Run with:  ruby 05_polymorphic.rb
#
# The grader always uses the official copy of this file, so editing it
# cannot make anything pass. Reading it is encouraged: the tests below
# are the specification.
# ----------------------------------------------------------------------------

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"
  gem "activerecord", "~> 8.1"
  gem "sqlite3", "~> 2.9"
end

require "active_record"
require "minitest/autorun"

ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.belongs_to_required_by_default = true # same default as a real Rails app
ActiveRecord::Migration.verbose = false

# ----------------------------------------------------------------------------
# SCHEMA — note: comments has no post_id and no photo_id
# ----------------------------------------------------------------------------

ActiveRecord::Schema.define do
  create_table :posts do |t|
    t.string :title, null: false
  end

  create_table :photos do |t|
    t.string :caption, null: false
  end

  create_table :comments do |t|
    t.text    :body, null: false
    t.string  :commentable_type
    t.integer :commentable_id
  end
end

# ----------------------------------------------------------------------------
# MODELS — your work, loaded from the one file you edit
# ----------------------------------------------------------------------------

require_relative "models/05_polymorphic"

# ----------------------------------------------------------------------------
# TESTS — ordered easy to hard
# ----------------------------------------------------------------------------

class PolymorphicTest < Minitest::Test
  def self.test_order = :alpha

  def setup
    Comment.delete_all
    Photo.delete_all
    Post.delete_all

    @post  = Post.create!(title: "Hello world")
    @photo = Photo.create!(caption: "Sunset over the bay")
  end

  def test_1_a_post_has_comments
    Comment.create!(body: "First!", commentable_type: "Post", commentable_id: @post.id)

    assert_equal ["First!"], @post.comments.map(&:body),
      "Post#comments must find the comments whose type AND id point at this post"
  end

  def test_2_the_same_comment_class_serves_photos
    Comment.create!(body: "Gorgeous light", commentable_type: "Photo", commentable_id: @photo.id)

    assert_equal ["Gorgeous light"], @photo.comments.map(&:body),
      "one Comment model must serve Photo exactly as it serves Post — " \
      "that is the whole point of polymorphic"
  end

  def test_3_a_comment_knows_what_it_belongs_to
    comment = Comment.create!(body: "First!", commentable_type: "Post", commentable_id: @post.id)

    assert_instance_of Post, comment.commentable,
      "Comment#commentable must return the actual Post object, rebuilt from " \
      "the type and id columns"
    assert_equal @post, comment.commentable,
      "and it must be THIS post, not just any post"
  end

  def test_4_creating_through_the_association_fills_both_columns
    comment = @photo.comments.create!(body: "Wow")

    assert_equal "Photo", comment.commentable_type,
      "photo.comments.create! must fill in commentable_type by itself"
    assert_equal @photo.id, comment.commentable_id,
      "…and commentable_id too. One column without the other points at nothing."
  end

  def test_5_a_post_and_a_photo_with_the_same_id_do_not_share_comments
    assert_equal @post.id, @photo.id,
      "(sanity check: the first post and the first photo have the same id — " \
      "that is exactly the situation this test is about)"

    @post.comments.create!(body: "On the post")
    @photo.comments.create!(body: "On the photo")

    assert_equal ["On the post"], @post.comments.map(&:body),
      "post 1 and photo 1 share an id — only commentable_type keeps their " \
      "comments apart. Filter by id alone and comments leak between models."
    assert_equal ["On the photo"], @photo.comments.map(&:body),
      "the photo must see only its own comment, not the post's"
  end

  def test_6_destroying_a_post_destroys_only_its_comments
    @post.comments.create!(body: "On the post")
    @photo.comments.create!(body: "On the photo")

    @post.destroy

    assert_equal 0, Comment.where(commentable_type: "Post").count,
      "destroying a post must destroy its comments — the database cannot " \
      "cascade this for you (ask yourself why: it is question 2)"
    assert_equal 1, Comment.count,
      "the photo's comment must survive — same id, different type, different owner"
  end
end
