# ----------------------------------------------------------------------------
# Challenge 06 — Single Table Inheritance — runner (schema + tests)
#
# DO NOT EDIT THIS FILE. Your work goes in models/06_sti.rb —
# the brief is there too. Run with:  ruby 06_sti.rb
#
# The grader always uses the official copy of this file, so editing it
# cannot make anything pass. Reading it is encouraged: the tests below
# are the specification.
#
# The tests use Article and Video, which do not exist until you create
# them. NameError failures are your starting point, not a crash.
# ----------------------------------------------------------------------------

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"
  gem "activerecord", "~> 8.1"
  gem "sqlite3", "~> 2.9"
end

require "active_record"
require "minitest/autorun"

ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Migration.verbose = false

# ----------------------------------------------------------------------------
# SCHEMA — one table for every kind of content. The `type` column is the
# STI switch: Rails stores the class name in it.
# ----------------------------------------------------------------------------

ActiveRecord::Schema.define do
  create_table :contents do |t|
    t.string  :type                                   # STI: holds the class name
    t.string  :title
    t.boolean :published, null: false, default: false
    t.text    :body                                   # only articles use this
    t.integer :duration_seconds                       # only videos use this
  end
end

# ----------------------------------------------------------------------------
# MODELS — your work, loaded from the one file you edit
# ----------------------------------------------------------------------------

require_relative "models/06_sti"

# ----------------------------------------------------------------------------
# TESTS — ordered easy to hard
# ----------------------------------------------------------------------------

class StiTest < Minitest::Test
  def self.test_order = :alpha

  def setup
    Content.delete_all

    @article     = Article.create!(title: "Rails tips", body: "Use scopes.", published: true)
    @video       = Video.create!(title: "Rails screencast", duration_seconds: 300, published: true)
    @draft_video = Video.create!(title: "Unfinished take", duration_seconds: 60)
  end

  def test_1_everything_lives_in_one_table
    assert_equal 3, Content.count,
      "an Article IS a Content, a Video IS a Content — one table holds " \
      "every row, and the parent class sees them all"
  end

  def test_2_the_type_column_remembers_the_class
    assert_equal "Article", @article.reload.type,
      "you never set type — Rails writes the class name there on save"
    assert_instance_of Video, Content.find(@video.id),
      "Content.find must give the row back as a Video, not a plain Content — " \
      "the type column tells Rails which class to build"
  end

  def test_3_subclass_queries_scope_themselves
    assert_equal ["Rails screencast", "Unfinished take"], Video.all.map(&:title).sort,
      "Video.all must return only videos, even though they share the table"
    assert_equal 1, Article.count,
      "Article.count must count only articles — you never wrote a WHERE " \
      "type clause; check the logger to see who did"
  end

  def test_4_shared_rules_live_on_the_parent_written_once
    refute Content.new(published: true).valid?,
      "every content needs a title, and the rule must live on Content itself — " \
      "if you copy-pasted it into Article and Video instead, this line catches you"
    refute Video.new(duration_seconds: 45).valid?,
      "a video with no title must be invalid — the subclass inherits the " \
      "parent's rule without repeating it"
  end

  def test_5_each_subclass_adds_only_its_own_rules
    refute Video.new(title: "Silent clip").valid?,
      "a video needs a duration"
    refute Article.new(title: "How to").valid?,
      "an article needs a body"
    assert Article.new(title: "How to", body: "Like this.").valid?,
      "an article must NOT need a duration — if it does, the duration rule " \
      "is sitting on the wrong class"
    assert Video.new(title: "Clip", duration_seconds: 5).valid?,
      "a video must NOT need a body — same reason, other direction"
  end

  def test_6_one_scope_narrows_by_class_automatically
    assert_equal ["Rails screencast", "Rails tips"], Content.published.map(&:title).sort,
      "Content.published sees published contents of every kind"
    assert_equal ["Rails screencast"], Video.published.map(&:title),
      "the SAME scope, called on Video, must return only published videos. " \
      "You wrote no type filter — STI adds it under every query the subclass " \
      "makes. This is what a hand-rolled kind column never gives you."
  end
end
