# ----------------------------------------------------------------------------
# Challenge 07 — Callbacks — runner (schema + tests)
#
# DO NOT EDIT THIS FILE. Your work goes in models/07_callbacks.rb —
# the brief is there too. Run with:  ruby 07_callbacks.rb
#
# The grader always uses the official copy of this file, so editing it
# cannot make anything pass. Reading it is encouraged: the tests below
# are the specification.
#
# Note: outside a Rails app, Time.current needs ActiveSupport loaded by
# hand — that is what the two active_support requires below are for.
# ----------------------------------------------------------------------------

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"
  gem "activerecord", "~> 8.1"
  gem "sqlite3", "~> 2.9"
end

require "active_record"
require "active_support"
require "active_support/time" # Time.current
require "minitest/autorun"

ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Migration.verbose = false

# ----------------------------------------------------------------------------
# SCHEMA
# ----------------------------------------------------------------------------

ActiveRecord::Schema.define do
  create_table :articles do |t|
    t.string   :title
    t.string   :slug
    t.boolean  :published, null: false, default: false
    t.datetime :published_at
    t.boolean  :locked, null: false, default: false
  end
end

# ----------------------------------------------------------------------------
# MODELS — your work, loaded from the one file you edit
# ----------------------------------------------------------------------------

require_relative "models/07_callbacks"

# ----------------------------------------------------------------------------
# TESTS — ordered easy to hard
# ----------------------------------------------------------------------------

class CallbacksTest < Minitest::Test
  def self.test_order = :alpha

  def setup
    Article.delete_all
  end

  def test_1_titles_are_stripped
    article = Article.create!(title: "  Hello  ")

    assert_equal "Hello", article.title,
      "the spaces around the title must be gone by the time it is saved"
  end

  def test_2_a_title_of_only_spaces_is_no_title
    refute Article.new(title: "   ").valid?,
      "after stripping, '   ' is blank — and a blank title must fail the " \
      "presence check. If this fails, your stripping runs too LATE: " \
      "validation already saw the spaces and waved them through."
  end

  def test_3_the_slug_is_built_from_the_title
    assert_equal "hello-world", Article.create!(title: "Hello, World!").slug,
      "downcase, squeeze every run of non-letters into one hyphen, " \
      "no hyphen at either end"
    assert_equal "rails-8-tips", Article.create!(title: "Rails 8 Tips").slug,
      "digits are part of a slug — do not strip them"
  end

  def test_4_publishing_stamps_the_time_and_drafts_have_none
    published = Article.create!(title: "Launch", published: true)
    draft     = Article.create!(title: "Someday")

    refute_nil published.published_at,
      "saving a published article must stamp published_at with the current time"
    assert_nil draft.published_at,
      "a draft has no publish date — do not stamp it"
  end

  def test_5_the_publish_stamp_never_moves
    article = Article.create!(title: "Launch", published: true)
    first_stamp = article.reload.published_at

    sleep 0.01
    article.update!(title: "Launch day!")

    assert_equal first_stamp, article.reload.published_at,
      "published_at is a historical fact — editing the article next week " \
      "must not move it. Stamp it once, then leave it alone."
  end

  def test_6_locked_articles_refuse_to_die
    unlocked = Article.create!(title: "Old news")
    locked   = Article.create!(title: "Legal page", locked: true)

    assert unlocked.destroy,
      "an unlocked article destroys normally"

    refute locked.destroy,
      "destroying a locked article must be halted and return false — " \
      "if the record died anyway, your callback did not halt the chain: " \
      "returning false stopped working in Rails 5, halting has its own mechanism"
    assert Article.exists?(locked.id),
      "the locked article must still be in the database"
  end
end
