# ----------------------------------------------------------------------------
# Challenge 08 — Transactions — runner (schema + tests)
#
# DO NOT EDIT THIS FILE. Your work goes in models/08_transactions.rb —
# the brief is there too. Run with:  ruby 08_transactions.rb
#
# The grader always uses the official copy of this file, so editing it
# cannot make anything pass. Reading it is encouraged: the tests below
# are the specification.
#
# Tests 4 and 5 sabotage one half of the transfer on purpose (they mark
# one account readonly, so writing to it raises). That is how we check
# the OTHER half gets undone. Real transfers fail halfway too — a
# validation, a constraint, a crash — just less politely.
# ----------------------------------------------------------------------------

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"
  gem "activerecord", "~> 8.1"
  gem "sqlite3", "~> 2.9"
end

require "active_record"
require "minitest/autorun"

ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Migration.verbose = false

# ----------------------------------------------------------------------------
# SCHEMA — the database refuses negative balances all by itself.
# Your code checks too; question 4 asks why both.
# ----------------------------------------------------------------------------

ActiveRecord::Schema.define do
  create_table :accounts do |t|
    t.string  :name, null: false
    t.integer :balance_cents, null: false, default: 0
    t.check_constraint "balance_cents >= 0", name: "no_overdraft"
  end
end

# ----------------------------------------------------------------------------
# MODELS — your work, loaded from the one file you edit
# ----------------------------------------------------------------------------

require_relative "models/08_transactions"

# ----------------------------------------------------------------------------
# TESTS — ordered easy to hard
# ----------------------------------------------------------------------------

class TransactionsTest < Minitest::Test
  def self.test_order = :alpha

  def setup
    Account.delete_all

    @reader = Account.create!(name: "Reader",  balance_cents: 500)
    @author = Account.create!(name: "Author",  balance_cents: 100)
  end

  def test_1_a_transfer_moves_the_money
    @reader.transfer_to!(@author, 200)

    assert_equal 300, @reader.reload.balance_cents,
      "the sender must end up 200 cents lighter"
    assert_equal 300, @author.reload.balance_cents,
      "…and the receiver 200 cents heavier. Money moves, it is not copied."
  end

  def test_2_the_amount_must_be_positive
    assert_raises(ArgumentError) { @reader.transfer_to!(@author, 0) }
    assert_raises(ArgumentError) { @reader.transfer_to!(@author, -50) }

    assert_equal 500, @reader.reload.balance_cents,
      "a rejected transfer must leave the sender untouched"
    assert_equal 100, @author.reload.balance_cents,
      "…and the receiver too. A transfer of -50 that 'worked' would be " \
      "a way to pull money OUT of someone else's account."
  end

  def test_3_you_cannot_send_money_you_do_not_have
    assert_raises(Account::InsufficientFunds,
      "overdrawing must raise YOUR error class, so callers can rescue it " \
      "specifically and show the user a decent message") do
      @reader.transfer_to!(@author, 9_999)
    end

    assert_equal 500, @reader.reload.balance_cents,
      "a failed transfer changes nothing"
    assert_equal 100, @author.reload.balance_cents,
      "a failed transfer changes nothing — on either side"
  end

  def test_4_when_the_credit_fails_the_debit_is_undone
    @author.readonly! # the receiving row cannot be written — the credit will raise

    assert_raises(ActiveRecord::ReadOnlyRecord,
      "writing to the readonly receiver must blow up mid-transfer — " \
      "that explosion, not a polite return, is what this test needs") do
      @reader.transfer_to!(@author, 200)
    end

    assert_equal 500, @reader.reload.balance_cents,
      "the debit went through and then the credit blew up — without a " \
      "transaction, 200 cents just left the sender and arrived NOWHERE. " \
      "Wrap both writes so the database undoes the first when the second fails."
    assert_equal 100, @author.reload.balance_cents,
      "the receiver was never paid — its balance must be untouched"
  end

  def test_5_when_the_debit_fails_the_credit_is_undone
    @reader.readonly! # now it is the SENDING row that cannot be written

    assert_raises(ActiveRecord::ReadOnlyRecord,
      "writing to the readonly sender must blow up mid-transfer") do
      @reader.transfer_to!(@author, 200)
    end

    assert_equal 100, @author.reload.balance_cents,
      "the credit went through and then the debit blew up — without a " \
      "transaction you just INVENTED 200 cents. Same fix, other direction: " \
      "both writes inside one transaction, whichever order you wrote them in."
    assert_equal 500, @reader.reload.balance_cents,
      "the sender never paid — its balance must be untouched"
  end
end
