# ----------------------------------------------------------------------------
# Challenge 09 — N+1 queries — runner (schema + tests)
#
# DO NOT EDIT THIS FILE. Your work goes in models/09_n_plus_one.rb —
# the brief is there too. Run with:  ruby 09_n_plus_one.rb
#
# The grader always uses the official copy of this file, so editing it
# cannot make anything pass. Reading it is encouraged: the tests below
# are the specification.
#
# These tests COUNT SQL queries (see count_queries below). Getting the
# right answer is not enough — you must get it in the right number of
# trips to the database.
# ----------------------------------------------------------------------------

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"
  gem "activerecord", "~> 8.1"
  gem "sqlite3", "~> 2.9"
end

require "active_record"
require "minitest/autorun"

ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.belongs_to_required_by_default = true # same default as a real Rails app
ActiveRecord::Migration.verbose = false

# ----------------------------------------------------------------------------
# SCHEMA
# ----------------------------------------------------------------------------

ActiveRecord::Schema.define do
  create_table :authors do |t|
    t.string :name, null: false
  end

  create_table :posts do |t|
    t.string   :title, null: false
    t.integer  :author_id
    t.datetime :created_at
  end

  create_table :comments do |t|
    t.text    :body, null: false
    t.integer :post_id
  end
end

# ----------------------------------------------------------------------------
# MODELS — your work, loaded from the one file you edit
# ----------------------------------------------------------------------------

require_relative "models/09_n_plus_one"

# ----------------------------------------------------------------------------
# TESTS — ordered easy to hard
# ----------------------------------------------------------------------------

class NPlusOneTest < Minitest::Test
  def self.test_order = :alpha

  # Counts every real SQL query the block runs. Schema lookups and
  # transaction bookkeeping do not count.
  def count_queries(&block)
    count = 0
    counter = lambda do |_name, _start, _finish, _id, payload|
      count += 1 unless %w[SCHEMA TRANSACTION].include?(payload[:name])
    end
    ActiveSupport::Notifications.subscribed(counter, "sql.active_record", &block)
    count
  end

  def setup
    Comment.delete_all
    Post.delete_all
    Author.delete_all

    now = Time.now
    @arya = Author.create!(name: "Arya")
    @brin = Author.create!(name: "Brin")

    # Note: @newest has a LOWER id than @middle but a LATER created_at.
    # Ordering by id gives the wrong feed. That is on purpose.
    @oldest = Post.create!(title: "Oldest", author_id: @arya.id, created_at: now - 300)
    @newest = Post.create!(title: "Newest", author_id: @brin.id, created_at: now)
    @middle = Post.create!(title: "Middle", author_id: @arya.id, created_at: now - 100)

    Comment.create!(body: "one",   post_id: @oldest.id)
    Comment.create!(body: "two",   post_id: @oldest.id)
    Comment.create!(body: "three", post_id: @oldest.id)
  end

  def test_1_the_feed_is_every_post_newest_first
    assert_equal ["Newest", "Middle", "Oldest"], Post.feed.map(&:title),
      "newest first means by created_at — one of these posts was inserted " \
      "out of order, so sorting by id looks right until it very much is not"
  end

  def test_2_the_feed_does_not_duplicate_busy_posts
    assert_equal Post.count, Post.feed.length,
      "the post with three comments must appear ONCE — a plain JOIN onto " \
      "comments multiplies the post by its comment count. Eager loading " \
      "and joining are not the same thing."
  end

  def test_3_after_the_feed_loads_rendering_is_free
    posts = Post.feed.to_a

    queries = count_queries do
      posts.each { |post| [post.author.name, post.comments.map(&:body)] }
    end

    assert_equal 0, queries,
      "the page already loaded the feed — showing each post's author and " \
      "comments must cost ZERO further queries. Every query counted here " \
      "is one the feed should have made up front."
  end

  def test_4_three_queries_no_matter_how_many_posts
    30.times do |i|
      post = Post.create!(title: "Bulk #{i}", author_id: @arya.id,
                          created_at: Time.now - 1000 - i)
      Comment.create!(body: "nice", post_id: post.id)
    end

    queries = count_queries do
      Post.feed.each { |post| [post.author.name, post.comments.length] }
    end

    assert_operator queries, :<=, 3,
      "three tables, three queries — posts, authors, comments — no matter " \
      "how many posts exist. If you counted ~30 or ~60, every single post " \
      "is going back to the database. That is the N+1, and at 10ms a query " \
      "it is the difference between a 30ms page and a 700ms page."
  end

  def test_5_by_author_filters_in_the_database
    relation = Post.by_author("Arya")

    assert_kind_of ActiveRecord::Relation, relation,
      "by_author must return a relation, so it can chain with the other scopes"
    assert_equal ["Middle", "Oldest"], relation.map(&:title).sort,
      "only Arya's posts, found by joining through to the authors table"

    queries = count_queries { Post.by_author("Brin").to_a }
    assert_equal 1, queries,
      "the DATABASE filters, in one query with a join — loading every post " \
      "and picking through them in Ruby also 'works', right up until the " \
      "table has a million rows"
  end
end
